# Generated by Django 5.2.9 on 2025-12-12 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('auto_pronta', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reparto',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tavolo',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa'), ('ANNULLATA', 'Annullata')], default='APERTA', max_length=10)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('creata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comande_create', to=settings.AUTH_USER_MODEL)),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comande', to='core.tavolo')),
            ],
            options={
                'db_table': 'comanda',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='core.reparto')),
            ],
            options={
                'db_table': 'prodotto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RigaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata'), ('PRONTA', 'Pronta'), ('SERVITA', 'Servita'), ('ANNULLATA', 'Annullata')], default='BOZZA', max_length=10)),
                ('inviata_il', models.DateTimeField(blank=True, null=True)),
                ('pronta_il', models.DateTimeField(blank=True, null=True)),
                ('servita_il', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='core.comanda')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_comanda', to='core.prodotto')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_comanda', to='core.reparto')),
            ],
            options={
                'db_table': 'riga_comanda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventoComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RIGA_CREATA', 'Riga creata'), ('RIGA_INVIATA', 'Riga inviata'), ('RIGA_PRONTA', 'Riga pronta'), ('RIGA_SERVITA', 'Riga servita'), ('RIGA_ANNULLATA', 'Riga annullata'), ('COMANDA_CHIUSA', 'Comanda chiusa')], max_length=30)),
                ('fatto_il', models.DateTimeField(auto_now_add=True)),
                ('dati', models.JSONField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='core.comanda')),
                ('fatto_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi_comanda', to=settings.AUTH_USER_MODEL)),
                ('riga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='core.rigacomanda')),
            ],
            options={
                'db_table': 'evento_comanda',
                'ordering': ['-fatto_il'],
            },
        ),
        migrations.AddIndex(
            model_name='rigacomanda',
            index=models.Index(fields=['reparto', 'stato'], name='idx_riga_rep_stato'),
        ),
        migrations.AddIndex(
            model_name='rigacomanda',
            index=models.Index(fields=['comanda'], name='idx_riga_comanda'),
        ),
        migrations.AddIndex(
            model_name='eventocomanda',
            index=models.Index(fields=['comanda', 'tipo'], name='idx_evt_comanda_tipo'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('stato', 'APERTA')), fields=('tavolo',), name='una_comanda_aperta_per_tavolo'),
        ),
    ]
