# Generated by Django 5.2.9 on 2025-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='coperti',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
