# Generated by Django 5.2.9 on 2025-12-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comanda_coperti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoComanda',
        ),
    ]
