# Generated by Django 5.2.9 on 2025-12-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_eventocomanda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='comanda',
            name='una_comanda_aperta_per_tavolo',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='chiusa_il',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='stato',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='tavolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commanda_corrente', to='core.tavolo'),
        ),
    ]
