# Generated by Django 5.2.9 on 2025-12-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comanda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='tavolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comanda_corrente', to='core.tavolo'),
        ),
    ]
